### ISSUE TITLE
AttributeError: 'cv2.CascadeClassifier' object has no attribute 'detectMultiScaleWithScores'

### ISSUE THREAD

**Issue by umitanuki** [eranid/adience_align#2]
After installing, I ran test_pipeline.py and failed.

```
... processing ./resources/pipeline/Fayssal_Mekdad_0002.jpg
E
======================================================================
ERROR: testPipeline (__main__.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_pipeline.py", line 30, in testPipeline
    cascade_face_aligner.detect_faces(input_folder, faces_folder)
  File "/usr/local/lib/python2.7/dist-packages/adiencealign/pipeline/CascadeFaceAligner.py", line 55, in detect_faces
    faces_file = self.face_finder.create_faces_file( input_file, is_overwrite = False, target_file = target_faces_file )
  File "/usr/local/lib/python2.7/dist-packages/adiencealign/cascade_detection/cascade_face_finder.py", line 104, in create_faces_file
    faces = self.get_faces_list_in_photo(cv2.imread(fname))
  File "/usr/local/lib/python2.7/dist-packages/adiencealign/cascade_detection/cascade_face_finder.py", line 89, in get_faces_list_in_photo
    haar_faces = self.haar_dtct.detectWithAngles(img, resolve = True)
  File "/usr/local/lib/python2.7/dist-packages/adiencealign/cascade_detection/cascade_detector.py", line 97, in detectWithAngles
    faces = self.detectMultiScaleWithScores(rot_image, scaleFactor = 1.03, minNeighbors = 20, minSize = (15,15), flags = 4)
  File "/usr/local/lib/python2.7/dist-packages/adiencealign/cascade_detection/cascade_detector.py", line 60, in detectMultiScaleWithScores
    return self._cascade_classifier.detectMultiScaleWithScores(img,
AttributeError: 'cv2.CascadeClassifier' object has no attribute 'detectMultiScaleWithScores'

----------------------------------------------------------------------
Ran 1 test in 0.051s
```

I don't think it has such method ever, but it looks like detectMultiScale (without WithScores)?  I changed it accordingly in my local and seems to be working.

**Comment by ahaque** [comment]
The following solved the problem for me:
I changed line 60 of `adience_align-master/adiencealign/cascade_detection/cascade_detector.py` to:
```
return self._cascade_classifier.detectMultiScale(img, 
												rejectLevels = [],
												levelWeights = [],
												scaleFactor = scaleFactor, 
												minNeighbors = minNeighbors, 
												minSize = minSize, 
												flags = flags, outputRejectLevels=True)
```
Notice the detectMultiScale change as well as the insertion of rejectLevels and levelWeights. Also see: 
http://haoxiang.org/2013/11/opencv-detectmultiscale-output-detection-score/

**Comment by mayankgrd** [comment]
Hi there, 
I faced similar error, and solved things as mentioned. But, it does not seem that the faces are aligned anymore. Specifically, see the Fayssal_Mekdad_0002_face_0.aligned imaged under the aligned folder. 

Any update on this? Though, I doubt that this might be causing problem. 

Any help will be highly appreciated.

**Comment by kli-nlpr** [comment]
I have the same problem

**Comment by kli-nlpr** [comment]
@umitanuki  @mayankgrd 
Have you solved this problem?

**Comment by sirnicolaz** [comment]
I have found the solution: the code is usuing an outdated version of the method. Just go to line 60 of `cascade_detector.py` and turn `detectMultiScaleWithScores` into `detectMultiScale`

**Comment by Lokesh3152** [comment]
i cant find cascade detector. i installed through conda can u help me out
